# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklisted', models.BooleanField(default=False)),
                ('administrativeComment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('competition', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=150)),
                ('issueDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20, verbose_name='Year you have taken the course')),
                ('instructor', models.CharField(blank=True, max_length=70, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField()),
                ('learnings', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='Years of Experience in this role')),
                ('cases', models.IntegerField(verbose_name='Number of engagements worked')),
                ('description', models.TextField(verbose_name='Brief outline of the relevant professional background')),
                ('priorClients', models.TextField(verbose_name='What key clients did you work with in this role?')),
                ('placesWorked', models.TextField(verbose_name='Where did you work from/at?')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150)),
                ('field_of_practice', models.CharField(choices=[('negotiation', 'Negotiation'), ('mediation', 'Mediation'), ('arbitration', 'Arbitratiion')], max_length=100)),
                ('employer', models.CharField(max_length=100, verbose_name='Name of Firm or Instituation')),
                ('country', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('duration', models.CharField(max_length=10, verbose_name='Duration of your Practice')),
                ('languages_used', models.CharField(max_length=250)),
                ('descr', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=5000)),
                ('country', models.CharField(max_length=100)),
                ('profileImg', models.ImageField(blank=True, upload_to='/profileImg/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('university_logo', models.ImageField(blank=True, upload_to='team/university_logo/')),
                ('country', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages_spoken', models.CharField(max_length=100)),
                ('presentation_text', models.TextField(max_length=4000)),
                ('application_letter', models.FileField(blank=True, null=True, upload_to='applications/teams/motivationletter/', verbose_name='Upload your motivation letter')),
                ('application_video', models.FileField(blank=True, null=True, upload_to='', verbose_name='Upload Application Video')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('attendent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserManagement.Attendent')),
                ('expertRole', models.CharField(choices=[('expert', 'Expert Assessor'), ('coach', 'Coach'), ('assessor', 'Assessor')], max_length=20)),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='coachedTeam', to='UserManagement.Team')),
            ],
            bases=('UserManagement.attendent',),
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserManagement.Profile')),
                ('slogan', models.TextField(blank=True, max_length=500)),
                ('affiliation', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('certifications', models.ManyToManyField(blank=True, to='UserManagement.Certification')),
                ('expert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Expert')),
            ],
            bases=('UserManagement.profile',),
        ),
        migrations.CreateModel(
            name='MediationExperience',
            fields=[
                ('experience_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserManagement.Experience')),
                ('profession', models.IntegerField(choices=[(1, 'Practicing Mediator'), (2, 'Mediation Trainer'), (3, 'Judged Mediation Competitions'), (4, 'NO prior Experience')])),
            ],
            bases=('UserManagement.experience',),
        ),
        migrations.CreateModel(
            name='NegotiationExperience',
            fields=[
                ('experience_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserManagement.Experience')),
                ('profession', models.IntegerField(choices=[(1, 'Practicing Negotiator'), (2, 'Negotiaton Trainer'), (3, 'Judged Negotiaton Competitions'), (4, 'NO prior Experience')])),
            ],
            bases=('UserManagement.experience',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('attendent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserManagement.Attendent')),
                ('shifts', models.CharField(max_length=200)),
            ],
            bases=('UserManagement.attendent',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('attendent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserManagement.Attendent')),
                ('studentRole', models.CharField(choices=[('negotiator', 'Negotiator'), ('mediator', 'Mediator')], max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Team')),
            ],
            bases=('UserManagement.attendent',),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserManagement.Profile')),
                ('slogan', models.CharField(max_length=250, verbose_name='Your favorite quote up to 250 characters')),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('Twitter', models.URLField(blank=True, null=True, verbose_name='Your Twitter Account')),
                ('Facebook', models.URLField(blank=True, null=True, verbose_name='Link to your Facebook Page')),
                ('Blog', models.URLField(blank=True, null=True, verbose_name='Link to a related professional Blog')),
                ('awards', models.ManyToManyField(blank=True, to='UserManagement.Award')),
                ('internships', models.ManyToManyField(blank=True, to='UserManagement.Internship')),
                ('mediation_courses', models.ManyToManyField(related_name='medCourses', to='UserManagement.Course')),
                ('negotiation_courses', models.ManyToManyField(related_name='negCourses', to='UserManagement.Course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Student')),
            ],
            bases=('UserManagement.profile',),
        ),
        migrations.AddField(
            model_name='attendent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='mediation_experience',
            field=models.ManyToManyField(blank=True, related_name='mediation_experience', to='UserManagement.MediationExperience'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='negotiation_experience',
            field=models.ManyToManyField(blank=True, related_name='negotiation_experience', to='UserManagement.NegotiationExperience'),
        ),
    ]
