# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='affiliation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
