# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_expertprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
