# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationDate', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Unreviewed'), (1, 'Reviewed'), (2, 'Selected'), (3, 'Accepted'), (4, 'Declined')])),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Attendent')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplicationManagement.Application')),
                ('reviewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
