# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_from', models.DateTimeField()),
                ('free_till', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('directions', models.TextField(max_length=2000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SessionManagement.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('street', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=5)),
                ('city', models.CharField(default='Vienna', max_length=50)),
                ('location_info', models.TextField(max_length=1000)),
                ('img_presentation', models.ImageField(upload_to='venues/presentationImg/')),
                ('img_venue', models.ImageField(upload_to='venues/locationImg/')),
                ('_internal_comments', models.TextField(blank=True, null=True)),
                ('rooms', models.ManyToManyField(to='SessionManagement.Room')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SessionManagement.Room'),
        ),
    ]
